#*****************************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# vivado.tcl: Tcl script for re-creating project 'project_2'
#
# Generated by Vivado on Sat Feb 14 15:48:49 CET 2026
# IP Build 6300035 on Fri Nov 14 10:48:45 MST 2025
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "croc_nexysa7"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

# Create project
create_project "croc_nexysa7" "vivado_project" -part xc7a100tcsg324-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "part" -value "xc7a100tcsg324-1" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj

# Reconstruct message rules
# None


# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dmi_intf.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_omega_net.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/onehot_to_bin.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_tracer_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_mux.sv"] \
 [file normalize "${origin_dir}/croc/rtl/test/tb_croc_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/id_queue.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_fork.sv"] \
 [file normalize "${origin_dir}/croc/rtl/apb/include/apb/typedef.svh"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/include/lowrisc_prim/prim_assert_standard_macros.svh"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_fork_dynamic.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/include/lowrisc_prim/prim_assert_yosys_macros.svh"] \
 [file normalize "${origin_dir}/croc/rtl/apb/include/apb/assign.svh"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_to_mem.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/isochronous_spill_register.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dmi_test.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/spill_register_flushable.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/apb_to_obi.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/plru_tree.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/lfsr.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_throttle.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/shift_reg_gated.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/credit_counter.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/ecc_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_intf.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/lfsr_8bit.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_core_tracing.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/passthrough_stream_fifo.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_join_dynamic.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/obi_to_apb.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/trip_counter.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/ring_buffer.sv"] \
 [file normalize "${origin_dir}/croc/rtl/apb/apb_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/lfsr_16bit.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/exp_backoff.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_register.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/cb_filter_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/isochronous_4phase_handshake.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/stream_xbar.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/cf_math_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/addr_decode.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/include/common_cells/assertions.svh"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/addr_decode_dync.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/obi_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/include/common_cells/registers.svh"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/cdc_2phase_clearable.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/cdc_4phase.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/cdc_reset_ctrlr_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/cdc_reset_ctrlr.sv"] \
 [file normalize "${origin_dir}/croc/rtl/clint/clint_reg_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/clint/clint.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/include/obi/typedef.svh"] \
 [file normalize "${origin_dir}/croc/rtl/croc_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dm_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/core_wrap.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/counter.sv"] \
 [file normalize "${origin_dir}/croc/rtl/croc_domain.sv"] \
 [file normalize "${origin_dir}/croc/rtl/croc_soc.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_alu.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/include/lowrisc_prim/prim_assert_sec_cm.svh"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/include/lowrisc_prim/prim_assert_dummy_macros.svh"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/include/lowrisc_prim/prim_assert.svh"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_compressed_decoder.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_controller.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_core.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_counter.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/include/cve2/cve2_pmp_reset_default.svh"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_cs_registers.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_csr.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_decoder.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_ex_block.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_fetch_fifo.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_id_stage.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_if_stage.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_load_store_unit.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_multdiv_fast.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_multdiv_slow.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_pmp.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_prefetch_buffer.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_register_file_ff.sv"] \
 [file normalize "${origin_dir}/croc/rtl/cve2/cve2_wb.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/debug_rom/debug_rom.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/debug_rom/debug_rom_one_scratch.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/delta_counter.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dm_csrs.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dm_mem.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dm_obi_top.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dm_sba.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dm_top.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dmi_cdc.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dmi_jtag.sv"] \
 [file normalize "${origin_dir}/croc/rtl/riscv-dbg/dmi_jtag_tap.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/fifo_v3.sv"] \
 [file normalize "${origin_dir}/croc/rtl/gpio/gpio_reg_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/gpio/gpio.sv"] \
 [file normalize "${origin_dir}/croc/rtl/gpio/gpio_reg_top.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/lzc.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/include/obi/assign.svh"] \
 [file normalize "${origin_dir}/croc/rtl/obi/obi_demux.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/obi_err_sbr.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/obi_intf.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/obi_mux.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/obi_sram_shim.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_timer/obi_timer_reg_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_timer/obi_timer.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_uart/obi_uart_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_uart/obi_uart.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_uart/obi_uart_baudgen.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_uart/obi_uart_interrupts.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_uart/obi_uart_modem.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_uart/obi_uart_register.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_uart/obi_uart_rx.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi_uart/obi_uart_tx.sv"] \
 [file normalize "${origin_dir}/croc/rtl/obi/obi_xbar.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/rr_arb_tree.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/rstgen.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/rstgen_bypass.sv"] \
 [file normalize "${origin_dir}/croc/rtl/soc_ctrl/soc_ctrl_regs_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/soc_ctrl/soc_ctrl_regs.sv"] \
 [file normalize "${origin_dir}/croc/rtl/common_cells/sync.sv"] \
 [file normalize "${origin_dir}/croc/rtl/tech_cells_generic/fpga/tc_clk_xilinx.sv"] \
 [file normalize "${origin_dir}/croc/rtl/tech_cells_generic/tc_sram_impl.sv"] \
 [file normalize "${origin_dir}/croc/rtl/tech_cells_generic/fpga/tc_sram_xilinx.sv"] \
 [file normalize "${origin_dir}/croc/rtl/user_pkg.sv"] \
 [file normalize "${origin_dir}/croc/rtl/user_domain.sv"] \
 [file normalize "${origin_dir}/src/croc_nexysa7.sv"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "include_dirs" -value "[file normalize "$origin_dir/croc/rtl/common_cells/include"] [file normalize "$origin_dir/croc/rtl/cve2/include"] [file normalize "$origin_dir/croc/rtl/obi/include"] [file normalize "$origin_dir/croc/rtl/apb/include"]" -objects $obj
set_property -name "top" -value "croc_nexysa7" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "verilog_define" -value "COMMON_CELLS_ASSERTS_OFF=1 SYNTHESIS=1 TARGET_SYNTHESIS=1" -objects $obj

read_ip "$origin_dir/src/clk_wiz_0.xci"

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/src/croc_nexysa7.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/src/croc_nexysa7.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

exit